### ISSUE TITLE
RequiredVersion of ConsoleGuiTools is outdated.

### ISSUE THREAD

**Issue by klennan** [gui-cs/F7History#17]
F7History.psd1 has a hardcoded dependency on v0.7.4 of ConsoleGuiTools, which is now at v0.7.5.35

I suggest using "ModuleVersion" instead of "RequiredVersion" to make a softer minimum version dependency.

**Comment by RH-TLagrone** [comment]
I am having the same issue.

[Microsoft.PowerShell.ConsoleGuiTools](https://www.powershellgallery.com/packages/Microsoft.PowerShell.ConsoleGuiTools) is now at version 0.7.6.0 as of 2023-10-27. This latest version includes the command `Show-ObjectTree`, which I am unable to use at the same time as F7History due to the version conflict.

I request allowing newer versions of Microsoft.PowerShell.ConsoleGuiTools as well. (i.e. replace the exact-version specifier `RequiredVersion` in F7History.psd1 with the minimum-version specifier `ModuleVersion` instead)

**Comment by tig** [comment]
Sorry about this folks.

I'm confused about `ModuleVersion` and `RequiredVersion` 

In order to build/test locally, I have a build script that looks at a local PS repo for ConsoleGuiTools and if found updates F7History.ps1 to force use of it (updating `RequiredVersion`). This is what I pushed to this repo.

Can you point me at docs that show how to effectively use `ModuleVersion` instead.?

**Comment by RH-TLagrone** [comment]
No worries! Here's the doc:

<https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_module_manifests#moduleversion>

Looking at your implementation, I think you could simply swap `RequiredVersion` for `ModuleVersion` and it would work just fine without needing any other changes.

**Comment by tig** [comment]
`v1.4` has been published. I think I did it right ;-).

I had to disable my CI/CD unit tests (which are pretty lame anyway) because of Pester v5 and me being confused. I'll fix those asap.

**Comment by tig** [comment]
Pretty sure v1.4.1 which was just published fixes this. 

https://www.powershellgallery.com/packages/F7History/1.4.1

**Comment by RH-TLagrone** [comment]
I can confirm that the issue is resolved. I am able to import and successfully use version 0.7.6.0 of the module Microsoft.PowerShell.ConsoleGuiTools simultaneously with version 1.4.1 of the module F7History.
